In [1]:
import torch

/home/halcyon/ProgramFiles/anaconda3/envs/ngsim/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
cond=torch.randn(2,2)
a=torch.zeros(2,2)
b=torch.ones(2,2)
print(cond,'\n',a,'\n',b)

tensor([[ 0.8651, -1.7235],
        [-0.2326, -0.5935]]) 
 tensor([[0., 0.],
        [0., 0.]]) 
 tensor([[1., 1.],
        [1., 1.]])


In [9]:
torch.where(cond>0,a,b)

tensor([[0., 1.],
        [1., 1.]])

## torch.gather

In [30]:
prob=torch.randn(4,20) #标准正态分布 维数
prob.shape

torch.Size([4, 20])

In [32]:
idx=prob.topk(dim=1,k=3)
idx.values.shape #[4,3]
idx

torch.return_types.topk(
values=tensor([[1.8251, 1.1618, 1.1585],
        [1.1913, 1.0538, 0.9340],
        [1.2529, 1.2489, 1.0719],
        [2.0312, 1.7732, 1.3777]]),
indices=tensor([[ 5,  1, 14],
        [14,  5, 19],
        [ 6,  1,  9],
        [13, 18, 19]]))

In [33]:
print(idx[0])
print(idx[1])

tensor([[1.8251, 1.1618, 1.1585],
        [1.1913, 1.0538, 0.9340],
        [1.2529, 1.2489, 1.0719],
        [2.0312, 1.7732, 1.3777]])
tensor([[ 5,  1, 14],
        [14,  5, 19],
        [ 6,  1,  9],
        [13, 18, 19]])


In [41]:
label=torch.arange(20)+100
print(label.shape)
print(label.expand(4,20))

torch.Size([20])
tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118, 119],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118, 119],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118, 119],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118, 119]])


In [42]:
torch.gather(input=label.expand(4,20),dim=1,index=idx[1])

tensor([[105, 101, 114],
        [114, 105, 119],
        [106, 101, 109],
        [113, 118, 119]])