In [1]:
import numpy as np
import torch

/home/halcyon/ProgramFiles/anaconda3/envs/ngsim/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.from_numpy()
np.array()

In [4]:
a=np.array([2,3.3])
b=torch.from_numpy(a)
b

tensor([2.0000, 3.3000], dtype=torch.float64)

In [5]:
a=np.ones([2,3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

torch.tensor() torch.FloatTensor([list])

注意 torch.tensor()可以表示int/float

torch.Tensor()默认是FloatTensor

In [21]:
torch.tensor([2,3.2])
torch.tensor([2,3])

tensor([2, 3])

In [17]:
torch.FloatTensor([2,3])

tensor([2., 3.])

In [12]:
torch.empty(1) #无限接近0

tensor([-1.2653e-35])

In [22]:
torch.Tensor([2,3])

tensor([2., 3.])

In [24]:
torch.IntTensor([2.,3.2])

/tmp/ipykernel_7974/308709110.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.IntTensor([2.,3.2])


tensor([2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1.2,3],dtype=int)

/tmp/ipykernel_7974/3171461209.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.2,3],dtype=int)


tensor([1, 3])

In [27]:
torch.randn([2,3])

tensor([[-0.6899,  1.4258, -0.3574],
        [ 1.1481,  1.0486,  0.9063]])

In [28]:
torch.full([1,2],1)

tensor([[1, 1]])

In [29]:
torch.full([2,1],1)

tensor([[1],
        [1]])

In [30]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [31]:
torch.range(0,10,2)

/tmp/ipykernel_7974/2765515675.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10,2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [33]:
print(torch.ones([2,1]))
print(torch.zeros([2,3]))
print(torch.eye(3))


tensor([[1.],
        [1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [37]:
torch.randperm(10)

tensor([2, 1, 8, 9, 3, 6, 5, 0, 4, 7])