In [5]:
import torch

/home/halcyon/ProgramFiles/anaconda3/envs/ngsim/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## try

In [6]:
a=torch.ones([2,3,4])
b=torch.ones(2,3,4)
a-b

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
a=torch.rand(2,3,4)
a[0].shape

torch.Size([3, 4])

In [8]:
a[0][0].shape

torch.Size([4])

## select first/last N

In [6]:
a=torch.randn(4,3,28,28)
a.shape

torch.Size([4, 3, 28, 28])

In [12]:
a[:2].shape #都从第0维开始

torch.Size([2, 3, 28, 28])

In [15]:
a[:2,:1,:-2:2,:].shape #和list的索引一样的!!!

torch.Size([2, 1, 13, 28])

## select by steps

In [7]:
a[:,:,:-1:2].shape
a[...,-1:2].shape

torch.Size([4, 3, 28, 0])

## select by mask

In [30]:
x=torch.randn(3,4)

=torch.eq(a,b)或者a.eq(b)

!=torch.ne

>torch.gt、<torch.lt、>=torch.ge、<=torch.le

In [35]:
mask=x.ge(0.5)
mask2=torch.ge(x,0.5)
print(mask)
print(mask2)

tensor([[False, False, False,  True],
        [ True, False, False, False],
        [ True, False, False, False]])
tensor([[False, False, False,  True],
        [ True, False, False, False],
        [ True, False, False, False]])


In [39]:
torch.masked_select(x,mask)

tensor([1.0941, 0.5097, 1.1499])

## select by flatten index

In [8]:
src=torch.tensor([[2,3,4],[3,4,5]])
src

tensor([[2, 3, 4],
        [3, 4, 5]])

In [10]:
torch.take(src,torch.arange(6))
torch.take(src,torch.tensor([1,2,3])) #下标拉平t


tensor([3, 4, 3])