In [1]:
import torch

/home/halcyon/ProgramFiles/anaconda3/envs/ngsim/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
a1=torch.randn(2,3,4)
a3=torch.randn(3,3,4)
a2=torch.randn(1,3,4)

In [12]:
torch.cat((a1,a3,a2),dim=0).shape

torch.Size([6, 3, 4])

In [13]:
a1=torch.randn(1,2)
a2=torch.randn(3,2)
print(a1)
print(a2)

tensor([[-0.0969,  0.8592]])
tensor([[-1.6247,  1.4070],
        [-0.5947,  0.0790],
        [ 0.5131,  0.8427]])


In [14]:
torch.cat([a1,a2],dim=0)

tensor([[-0.0969,  0.8592],
        [-1.6247,  1.4070],
        [-0.5947,  0.0790],
        [ 0.5131,  0.8427]])

In [17]:
torch.stack([a1,a1,a1],dim=0).shape

torch.Size([3, 1, 2])

In [18]:
a=torch.randn(32,8)
b=torch.randn(32,8)

In [19]:
c=torch.stack((a,b),dim=0)
c.shape

torch.Size([2, 32, 8])

In [21]:
aa,bb,cc=torch.split(c,[10,20,2],dim=1)
aa,bb,cc=c.split((10,20,2),dim=1)

In [25]:
aa,bb,cc,dd=torch.chunk(c,4,1)
print(aa.shape,bb.shape,cc.shape)

torch.Size([2, 8, 8]) torch.Size([2, 8, 8]) torch.Size([2, 8, 8])
