In [3]:
import torch
import torch.nn.functional as F

In [2]:
x=torch.ones(1)
w=torch.full([1],2)
print(x,'\n',w)

tensor([1.]) 
 tensor([2])


In [6]:
mse=F.mse_loss(torch.ones(1),x*w)
mse.type()

'torch.FloatTensor'

In [8]:
torch.autograd.grad(mse,w) #因为mse没有require_grad存grad值 所以必须要明确指出!!!

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [16]:
x=torch.ones(1).requires_grad_() #_说明是内置函数
w=torch.full([1],2)
mse=F.mse_loss(torch.ones(1),x*w)
torch.autograd.grad(mse,x)

(tensor([4.]),)

In [18]:
print(x.grad)

None


In [19]:
x.backward

<bound method Tensor.backward of tensor([1.], requires_grad=True)>

In [20]:
print(x.grad)

None


In [24]:
mse=F.mse_loss(torch.ones(1),x*w)
mse.backward()
x.grad

tensor([4.])

## softmax

In [25]:
a=torch.rand(3)
a

tensor([0.4364, 0.0706, 0.1390])

In [27]:
a.requires_grad_()

tensor([0.4364, 0.0706, 0.1390], requires_grad=True)

In [28]:
p=F.softmax(a,dim=0)
p

tensor([0.4104, 0.2847, 0.3049], grad_fn=<SoftmaxBackward0>)

In [31]:
# p.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [38]:
torch.autograd.grad(p[1],[a],retain_graph=True)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [39]:
torch.autograd.grad(p[2],[a])

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [41]:
torch.full([1,2,3],3.,requires_grad=True)

tensor([[[3., 3., 3.],
         [3., 3., 3.]]], requires_grad=True)