In [1]:
import torch

/home/halcyon/ProgramFiles/anaconda3/envs/ngsim/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a=torch.randn(3,4)
b=torch.randn(4)
print(a)
print(b)

tensor([[ 1.4550,  0.6488, -0.4486, -1.6204],
        [-0.7860, -0.5368, -0.4361, -0.3776],
        [-0.8394, -0.3851,  0.8052, -0.4962]])
tensor([ 0.7468, -0.3227, -0.7467,  1.2798])


In [4]:
a*2

tensor([[ 2.9100,  1.2975, -0.8972, -3.2408],
        [-1.5720, -1.0736, -0.8721, -0.7552],
        [-1.6788, -0.7701,  1.6105, -0.9923]])

In [5]:
a+1

tensor([[ 2.4550,  1.6488,  0.5514, -0.6204],
        [ 0.2140,  0.4632,  0.5639,  0.6224],
        [ 0.1606,  0.6149,  1.8052,  0.5038]])

In [7]:
torch.all(torch.eye(4))

tensor(False)

In [8]:
torch.all(torch.ones(4,4))

tensor(True)

In [14]:
b=torch.randn(3)

In [24]:
a=torch.randn(3,4,5)
b=torch.randn(4,5)
a*b

tensor([[[ 0.0064, -1.0044,  0.2598, -0.3646, -0.1275],
         [ 0.2040, -0.0940,  0.9170, -0.1541,  0.5788],
         [-0.0245,  1.4593, -0.0405,  0.3808,  2.1842],
         [-0.2481,  2.7257,  0.8660,  0.0580,  0.3524]],

        [[ 0.0896, -0.6051,  0.2085, -0.0308,  0.1516],
         [-0.0517,  0.1030,  0.1293, -0.0420, -0.0546],
         [-0.0028,  1.2874,  0.0095, -0.1751,  0.9286],
         [ 0.9112, -0.4765,  1.0075, -0.0494, -1.8575]],

        [[ 0.4925, -1.4378, -0.2774, -0.6650, -0.2553],
         [-0.0983, -0.0424,  1.3079,  0.0794,  0.0399],
         [-0.0144, -0.5169, -0.0360, -0.3373, -0.2055],
         [-0.3857, -2.4264, -0.1698, -0.2868, -2.3733]]])

In [26]:
a=torch.randn(2,2)
b=torch.randn(2,1)
a.mm(b)

tensor([[ 0.5711],
        [-1.9588]])

In [30]:
a=torch.randn(4,3,28,64)
b=torch.randn(4,3,64,32)
print(torch.matmul(a,b).shape,a.shape,b.shape,(a@b).shape)

torch.Size([4, 3, 28, 32]) torch.Size([4, 3, 28, 64]) torch.Size([4, 3, 64, 32]) torch.Size([4, 3, 28, 32])


In [39]:
a=torch.randn(5,6,7,8,9)
b=torch.randn(5,6,8,9,10,11)
# c=torch.randn(5,6,8)
(a@b).shape
# (a@c).shape

RuntimeError: The size of tensor a (7) must match the size of tensor b (9) at non-singleton dimension 3

In [41]:
torch.pow(a,2).shape

torch.Size([5, 6, 7, 8, 9])

In [44]:
d=torch.randn(3,2).pow(2).shape
d

torch.Size([3, 2])

In [46]:
a=torch.full((2,2),3)
a=a**2

In [47]:
a.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [48]:
a.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [50]:
torch.rand(2,3)*15

tensor([[14.7639, 13.4842,  0.3522],
        [ 4.2149,  8.9469,  3.0810]])

In [52]:
torch.clamp(torch.rand(2,3)*15,0,10)

tensor([[10.0000,  6.2547,  6.6705],
        [10.0000,  9.3751,  2.5215]])