## Tensor 维度变换

In [2]:
import torch

/home/halcyon/ProgramFiles/anaconda3/envs/ngsim/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## View/reshape

丢维度信息

In [3]:
a=torch.rand(4,1,28,28) #rand 生成均匀分布的伪随机数。分布在(0~1)之间主要语法:rand(m,n)生成m行n列的均匀分布的伪随机数,rand(m,n,'d...
# randn 生成标准正态分布的伪随机数(均值为0,方差为1)
a.shape

torch.Size([4, 1, 28, 28])

In [5]:
# b=torch.rand(1,2,3)
# print(b)
# print(torch.randn(1,2))

tensor([[[0.8169, 0.7721, 0.0737],
         [0.1124, 0.8476, 0.4285]]])
tensor([[-0.3564, -0.9953]])


In [8]:
a.view(4,28*28).shape
a.view(4*28,1,28).shape

torch.Size([112, 1, 28])

In [11]:
b=a.view(4,784)
b.view(4,28,28,1).shape #为什么 logic bug???? 只能压降维度,不能升高维度有问题

torch.Size([4, 28, 28, 1])

In [24]:
a=torch.rand(1,3,2)
print(a)

torch.float32

In [21]:
b=a.view(3,8)
b

tensor([[0.3639, 0.5460, 0.4463, 0.8858, 0.1683, 0.2863, 0.0665, 0.9243],
        [0.5405, 0.5960, 0.2534, 0.8836, 0.5191, 0.2870, 0.3682, 0.9355],
        [0.4313, 0.3078, 0.7532, 0.4840, 0.3093, 0.3262, 0.2667, 0.2077]])

In [22]:
b.view(2,3,4) #根本没变 和上面的b
b

tensor([[0.3639, 0.5460, 0.4463, 0.8858, 0.1683, 0.2863, 0.0665, 0.9243],
        [0.5405, 0.5960, 0.2534, 0.8836, 0.5191, 0.2870, 0.3682, 0.9355],
        [0.4313, 0.3078, 0.7532, 0.4840, 0.3093, 0.3262, 0.2667, 0.2077]])

In [25]:
print(a.type())
print(a.dtype)

torch.FloatTensor
torch.float32


In [26]:
a.view(3,7)

RuntimeError: shape '[3, 7]' is invalid for input of size 24

## squeeze

In [27]:
a.shape

torch.Size([4, 3, 2])

In [29]:
a.unsqueeze(2).shape

torch.Size([4, 3, 1, 2])

In [34]:
a.unsqueeze(4).shape #expected to be in range of [-4, 3] 正数0-3 倒数-4到-1

IndexError: Dimension out of range (expected to be in range of [-4, 3], but got 4)

In [35]:
b=a.unsqueeze(3)
b.shape

torch.Size([4, 3, 2, 1])

In [41]:
b.squeeze().shape #只压缩只有1个元素的维度

torch.Size([4, 3, 2])

## Expand / repeat

In [45]:
a.shape
a

tensor([[[0.1069, 0.8662],
         [0.0812, 0.3723],
         [0.1449, 0.6075]],

        [[0.1430, 0.4440],
         [0.3562, 0.0618],
         [0.5284, 0.8202]],

        [[0.6839, 0.0346],
         [0.5351, 0.8804],
         [0.5480, 0.4716]],

        [[0.3208, 0.5680],
         [0.6809, 0.8518],
         [0.6759, 0.1831]]])

In [49]:
a=torch.rand(4,32,14,14)
b=torch.rand(1,32,1,1)
print(a.shape,b.shape)

torch.Size([4, 32, 14, 14]) torch.Size([1, 32, 1, 1])


In [50]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [61]:
b.expand(-1,32,-1,50).shape 

torch.Size([1, 32, 1, 50])

In [64]:
a=torch.rand(4,3,2)
b=torch.rand(1,3,1)
print(a)
print(b)

tensor([[[0.7452, 0.1620],
         [0.5676, 0.0442],
         [0.4378, 0.4323]],

        [[0.4336, 0.8240],
         [0.0486, 0.7944],
         [0.4667, 0.5244]],

        [[0.9565, 0.8769],
         [0.0767, 0.1520],
         [0.5601, 0.3392]],

        [[0.6241, 0.5862],
         [0.0781, 0.4905],
         [0.1670, 0.6570]]])
tensor([[[0.1238],
         [0.2136],
         [0.2553]]])


In [66]:
b.expand(-1,3,4) #就是复制

tensor([[[0.1238, 0.1238, 0.1238, 0.1238],
         [0.2136, 0.2136, 0.2136, 0.2136],
         [0.2553, 0.2553, 0.2553, 0.2553]]])

repeat

In [69]:
b.repeat(2,2,2)

tensor([[[0.1238, 0.1238],
         [0.2136, 0.2136],
         [0.2553, 0.2553],
         [0.1238, 0.1238],
         [0.2136, 0.2136],
         [0.2553, 0.2553]],

        [[0.1238, 0.1238],
         [0.2136, 0.2136],
         [0.2553, 0.2553],
         [0.1238, 0.1238],
         [0.2136, 0.2136],
         [0.2553, 0.2553]]])

## transpose

In [71]:
a.shape

torch.Size([4, 3, 2])

In [73]:
a.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

In [75]:
b=torch.rand(2,3)
b.t()

tensor([[0.1973, 0.2449],
        [0.1858, 0.6914],
        [0.9855, 0.7725]])

In [78]:
a.transpose(1,2).shape

torch.Size([4, 2, 3])

In [80]:
print(a.transpose(1,2))
print(a.transpose(1,2).contiguous())
 #https://blog.csdn.net/qq_37828380/article/details/107855070 
 # 最好都加上.contiguous()开辟一个新的内存 拷贝一份内存地址,解决一维数组存储导致的下标不连续的问题

tensor([[[0.7452, 0.5676, 0.4378],
         [0.1620, 0.0442, 0.4323]],

        [[0.4336, 0.0486, 0.4667],
         [0.8240, 0.7944, 0.5244]],

        [[0.9565, 0.0767, 0.5601],
         [0.8769, 0.1520, 0.3392]],

        [[0.6241, 0.0781, 0.1670],
         [0.5862, 0.4905, 0.6570]]])
tensor([[[0.7452, 0.5676, 0.4378],
         [0.1620, 0.0442, 0.4323]],

        [[0.4336, 0.0486, 0.4667],
         [0.8240, 0.7944, 0.5244]],

        [[0.9565, 0.0767, 0.5601],
         [0.8769, 0.1520, 0.3392]],

        [[0.6241, 0.0781, 0.1670],
         [0.5862, 0.4905, 0.6570]]])


permute

In [88]:
a=torch.rand(4,3,38,38)
a.shape
b=a.permute(-1,-3,-2,-4).shape
b

torch.Size([38, 3, 38, 4])