In [1]:
import torch

/home/halcyon/ProgramFiles/anaconda3/envs/ngsim/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Normalization

https://blog.csdn.net/qq_39382877/article/details/98875822


In [21]:
a=torch.randint(-2,2,(2,2,3),dtype=float)
a

tensor([[[-2., -2.,  1.],
         [-1., -2.,  0.]],

        [[-1.,  1., -2.],
         [ 0., -1., -2.]]], dtype=torch.float64)

In [19]:
a.norm(3,dim=2).shape

torch.Size([2, 2])

In [24]:
a=torch.tensor([1,2])
a.prod()

tensor(2)

In [33]:
a=torch.randn(2,3,4)
a

tensor([[[-1.7665, -0.5123, -0.8416,  0.1253],
         [ 0.8669,  0.5936, -2.0026, -0.9076],
         [ 1.7972,  0.0321,  0.6369,  1.0454]],

        [[ 1.0656,  0.4649, -0.1323,  1.4071],
         [-1.9721, -0.9167,  1.0249,  0.8079],
         [ 0.2018,  0.3975,  0.5657, -0.7386]]])

In [47]:
a.max(dim=2,keepdim=True).indices.shape


torch.Size([2, 3, 1])

In [48]:
a.max(dim=2,keepdim=True)

torch.return_types.max(
values=tensor([[[0.1253],
         [0.8669],
         [1.7972]],

        [[1.4071],
         [1.0249],
         [0.5657]]]),
indices=tensor([[[3],
         [0],
         [0]],

        [[3],
         [2],
         [2]]]))

In [49]:
a

tensor([[[-1.7665, -0.5123, -0.8416,  0.1253],
         [ 0.8669,  0.5936, -2.0026, -0.9076],
         [ 1.7972,  0.0321,  0.6369,  1.0454]],

        [[ 1.0656,  0.4649, -0.1323,  1.4071],
         [-1.9721, -0.9167,  1.0249,  0.8079],
         [ 0.2018,  0.3975,  0.5657, -0.7386]]])

In [50]:
a.topk(3,dim=2)

torch.return_types.topk(
values=tensor([[[ 0.1253, -0.5123, -0.8416],
         [ 0.8669,  0.5936, -0.9076],
         [ 1.7972,  1.0454,  0.6369]],

        [[ 1.4071,  1.0656,  0.4649],
         [ 1.0249,  0.8079, -0.9167],
         [ 0.5657,  0.3975,  0.2018]]]),
indices=tensor([[[3, 1, 2],
         [0, 1, 3],
         [0, 3, 2]],

        [[3, 0, 1],
         [2, 3, 1],
         [2, 1, 0]]]))

In [51]:
a.topk(3,dim=2,largest=False) #排除最大的

torch.return_types.topk(
values=tensor([[[-1.7665, -0.8416, -0.5123],
         [-2.0026, -0.9076,  0.5936],
         [ 0.0321,  0.6369,  1.0454]],

        [[-0.1323,  0.4649,  1.0656],
         [-1.9721, -0.9167,  0.8079],
         [-0.7386,  0.2018,  0.3975]]]),
indices=tensor([[[0, 2, 1],
         [2, 3, 1],
         [1, 2, 3]],

        [[2, 1, 0],
         [0, 1, 3],
         [3, 0, 1]]]))

In [55]:
a

tensor([[[-1.7665, -0.5123, -0.8416,  0.1253],
         [ 0.8669,  0.5936, -2.0026, -0.9076],
         [ 1.7972,  0.0321,  0.6369,  1.0454]],

        [[ 1.0656,  0.4649, -0.1323,  1.4071],
         [-1.9721, -0.9167,  1.0249,  0.8079],
         [ 0.2018,  0.3975,  0.5657, -0.7386]]])

In [59]:
a.kthvalue(2,dim=2,keepdim=True,larges) #k-th 最小元素

torch.return_types.kthvalue(
values=tensor([[[-0.8416],
         [-0.9076],
         [ 0.6369]],

        [[ 0.4649],
         [-0.9167],
         [ 0.2018]]]),
indices=tensor([[[2],
         [3],
         [2]],

        [[1],
         [1],
         [0]]]))